import random
rhe = (random.randint(2, 6))
rfe = (random.randint(1, 5))
rhe2 = round(rhe, 0)
rfe2 = round(rfe, 0)
def main():
    lines = open('homeless.txt').read().splitlines()
    myline = random.choice(lines)
    if myline == ('Guy asks for you to hold onto expensive vase (stolen)'):
        print("A man asks you to hold  onto a rather expensive looking vase")
         a = (random.randint(1, 2))
        if a == (1):
            print ("    The police seem to be quite interestind in the vase, and accuse you of stealing it!");
        if a == (2): 
            b = (random.randint(75, 100))
            print("    The man returns after a short while, and gives you", b, " dollars.")
    else:
        myline == ('Guy asks for you to hold onto expensive vase (stolen)')
        input()
if __name__ == '__main__':
    main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
main()
